---

postgres_listen_address: 'localhost,10.132.14.83'
postgres_extra_packages:
  - pgtop

postgres_clients:
  - {db: sirbot, user: sirbot, address: 10.132.119.69/32}
  - {db: sirbot, user: sirbot, address: 10.132.135.249/32}
  - {db: pyslackersweb, user: pyslackersweb, address: 10.132.54.169/32}
